
// generated by /home/ryan/src/third-party/VUE/VUE2/src/build.xml
package tufts.vue;
/** generated by /home/ryan/src/third-party/VUE/VUE2/src/build.xml February 27 2019 1526 */
public final class Version {
/** February 27 2019 at 1526 by ryan on Linux 4.19.0-0.bpo.2-amd64 amd64 JVM 1.8.0_181-8u181-b13-2~deb9u1-b13 */
public static final String
        Date = "February 27 2019",
        Time = "1526",
        User = "ryan",
        Platform = "Linux 4.19.0-0.bpo.2-amd64 amd64",
        JVM = "1.8.0_181-8u181-b13-2~deb9u1-b13(bits=64)",
        AllInfo = "February 27 2019 at 1526 by ryan on " + Platform + " JVM " + JVM,
        WhatString = "@(#)VUE: built " + AllInfo;
}
