package tufts.oki.id;

public class Id
implements org.osid.shared.Id
{
    private String idString = null;

    protected Id()
    throws org.osid.shared.SharedException
    {
        /*
            There are many ways to implement unique ids.  This particular implementation is using
            a unique id generated by the Java RMI Server and rearranging it a bit.  The IP address
            of the local host is added in.
        */
        java.rmi.server.UID uid = new java.rmi.server.UID();
        idString = uid.toString();
        // rearrange to show greatest variability first, format ###:###:-###
        try
        {
            java.util.StringTokenizer st = new java.util.StringTokenizer(idString,":");
            int tokenCount = 0;
            String a = "";
            String b = "";
            String c = "";
            while(st.hasMoreTokens())
            {
                if (tokenCount == 0) a = st.nextToken();
                else if (tokenCount == 1) b = st.nextToken();
                else c = st.nextToken();
                tokenCount++;
            }
            String b1 = "";
            for (int i=0; i < b.length(); i++) b1 = b.substring(i,i+1) + b1;
            idString = b1+c+a;
            idString = idString.replace('-','0');
            // add a suffix for the local host, removing all but IP address without periods
            String ip = java.net.InetAddress.getLocalHost().toString();
            int pos = ip.indexOf("/");
            ip = ip.substring(pos + 1);
            ip = ip.replace('.','0');
            idString = idString + ip;
        }
        catch (Throwable t) 
        {
            throw new org.osid.shared.SharedException(org.osid.shared.SharedException.OPERATION_FAILED);    
        }
    }

    protected Id(String idString)
    throws org.osid.shared.SharedException
    {
        if (idString == null)
        {
            throw new org.osid.shared.SharedException(org.osid.id.IdException.NULL_ARGUMENT);    
        }
        this.idString = idString;
    }

    public String getIdString()
    throws org.osid.shared.SharedException
    {
        return this.idString;
    }

    public boolean isEqual(org.osid.shared.Id id)
    throws org.osid.shared.SharedException
    {
        return id.getIdString().equals(this.idString);
    }
/**
<p>MIT O.K.I&#46; SID Implementation License.
  <p>	<b>Copyright and license statement:</b>
  </p>  <p>	Copyright &copy; 2003 Massachusetts Institute of
	Technology &lt;or copyright holder&gt;
  </p>  <p>	This work is being provided by the copyright holder(s)
	subject to the terms of the O.K.I&#46; SID Implementation
	License. By obtaining, using and/or copying this Work,
	you agree that you have read, understand, and will comply
	with the O.K.I&#46; SID Implementation License. 
  </p>  <p>	THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
	KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
	MASSACHUSETTS INSTITUTE OF TECHNOLOGY, THE AUTHORS, OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
	OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
	OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
	THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
  </p>  <p>	<b>O.K.I&#46; SID Implementation License</b>
  </p>  <p>	This work (the &ldquo;Work&rdquo;), including software,
	documents, or other items related to O.K.I&#46; SID
	implementations, is being provided by the copyright
	holder(s) subject to the terms of the O.K.I&#46; SID
	Implementation License. By obtaining, using and/or
	copying this Work, you agree that you have read,
	understand, and will comply with the following terms and
	conditions of the O.K.I&#46; SID Implementation License:
  </p>  <p>	Permission to use, copy, modify, and distribute this Work
	and its documentation, with or without modification, for
	any purpose and without fee or royalty is hereby granted,
	provided that you include the following on ALL copies of
	the Work or portions thereof, including modifications or
	derivatives, that you make:
  </p>  <ul>	<li>	  The full text of the O.K.I&#46; SID Implementation
	  License in a location viewable to users of the
	  redistributed or derivative work.
	</li>  </ul>  <ul>	<li>	  Any pre-existing intellectual property disclaimers,
	  notices, or terms and conditions. If none exist, a
	  short notice similar to the following should be used
	  within the body of any redistributed or derivative
	  Work: &ldquo;Copyright &copy; 2003 Massachusetts
	  Institute of Technology. All Rights Reserved.&rdquo;
	</li>  </ul>  <ul>	<li>	  Notice of any changes or modifications to the
	  O.K.I&#46; Work, including the date the changes were
	  made. Any modified software must be distributed in such
	  as manner as to avoid any confusion with the original
	  O.K.I&#46; Work.
	</li>  </ul>  <p>	THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
	KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
	MASSACHUSETTS INSTITUTE OF TECHNOLOGY, THE AUTHORS, OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
	OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
	OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
	THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
  </p>  <p>	The name and trademarks of copyright holder(s) and/or
	O.K.I&#46; may NOT be used in advertising or publicity
	pertaining to the Work without specific, written prior
	permission. Title to copyright in the Work and any
	associated documentation will at all times remain with
	the copyright holders.
  </p>  <p>	The export of software employing encryption technology
	may require a specific license from the United States
	Government. It is the responsibility of any person or
	organization contemplating export to obtain such a
	license before exporting this Work.
  </p>
*/
}
