
// generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml
package tufts.vue;
/** generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml April 15 2011 1945 */
public final class Version {
/** April 15 2011 at 1945 by helenoliver on Mac OS X 10.6.7 x86_64 JVM 1.6.0_24-b07-334-10M3326 */
public static final String
        Date = "April 15 2011",
        Time = "1945",
        User = "helenoliver",
        Platform = "Mac OS X 10.6.7 x86_64",
        JVM = "1.6.0_24-b07-334-10M3326(bits=64)",
        AllInfo = "April 15 2011 at 1945 by helenoliver on " + Platform + " JVM " + JVM,
        WhatString = "@(#)VUE: built " + AllInfo;
}
