
// generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml
package tufts.vue;
/** generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml November 24 2011 1716 */
public final class Version {
/** November 24 2011 at 1716 by helenoliver on Mac OS X 10.6.8 x86_64 JVM 1.6.0_29-b11-402-10M3527 */
public static final String
        Date = "November 24 2011",
        Time = "1716",
        User = "helenoliver",
        Platform = "Mac OS X 10.6.8 x86_64",
        JVM = "1.6.0_29-b11-402-10M3527(bits=64)",
        AllInfo = "November 24 2011 at 1716 by helenoliver on " + Platform + " JVM " + JVM,
        WhatString = "@(#)VUE: built " + AllInfo;
}
