
// generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml
package tufts.vue;
/** generated by /Users/helenoliver/tuftsvue/trunk/VUE2/src/build.xml February 21 2012 1211 */
public final class Version {
/** February 21 2012 at 1211 by helenoliver on Mac OS X 10.6.8 x86_64 JVM 1.6.0_29-b11-402-10M3527 */
public static final String
        Date = "February 21 2012",
        Time = "1211",
        User = "helenoliver",
        Platform = "Mac OS X 10.6.8 x86_64",
        JVM = "1.6.0_29-b11-402-10M3527(bits=64)",
        AllInfo = "February 21 2012 at 1211 by helenoliver on " + Platform + " JVM " + JVM,
        WhatString = "@(#)VUE: built " + AllInfo;
}
