# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [master, gradle-and-fixes]
  pull_request:
    branches: [master, gradle-and-fixes]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update version for CI snapshot
        run: .github/workflows/make-snapshot-version.sh
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Windows executable with launch4j
        run: ./gradlew createExe
      # Artifact upload disabled to avoid violating licenses - see https://github.com/VUE/VUE/issues/49
      # - name: Upload jar
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: jar
      #     path: VUE2/build/libs
      # - name: Upload bundles
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: bundles
      #     path: VUE2/build/distributions
      # - name: Upload Windows executable
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: windows
      #     path: VUE2/build/launch4j
